package com.ecommerceproject.dubaimagazinesalvador.domain.produto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public record ProdutoResponseDTO(
        String codigoSantri,
        String nome,
        String nomeExibidoSite,
        String ncm,
        String nomeCompra,
        String fabricante,
        String marca,
        boolean ativoSantri,
        String unidadeVenda,
        String unidadeCompra,
        LocalDate dataCadastro,
        String codigoOriginal,
        String codigoBarras,
        boolean bloqueadoParaCompras,
        BigDecimal estoque,
        BigDecimal precoSemIpi,
        BigDecimal percentualIpiEntrada,
        BigDecimal precoComIpi,
        BigDecimal pesoUnidade,
        BigDecimal alturaUnidade,
        BigDecimal larguraUnidade,
        BigDecimal comprimentoUnidade,
        BigDecimal volumeUnidadeM3,
        BigDecimal volumeLitros,
        BigDecimal pesoCaixa,
        BigDecimal alturaCaixa,
        BigDecimal larguraCaixa,
        BigDecimal comprimentoCaixa,
        String origem,
        Boolean industrializado,
        Boolean insumo,
        BigDecimal percentualMaximoAproveitamentoIpi,
        String numeroFci,
        String categoriaCodigo,
        String categoriaNome,
        String categoriaCaminho,
        String imagemUrl,
        boolean exibirNoSite,
        boolean destaqueNaHome,
        boolean disponivelUltimaImportacao,
        LocalDateTime ultimaImportacaoEm
) {

    public ProdutoResponseDTO(Produto produto) {
        this(
                produto.getCodigoSantri(),
                produto.getNome(),
                produto.getNomeExibidoSite(),
                produto.getNcm(),
                produto.getNomeCompra(),
                produto.getFabricante(),
                produto.getMarca(),
                produto.isAtivoSantri(),
                produto.getUnidadeVenda(),
                produto.getUnidadeCompra(),
                produto.getDataCadastro(),
                produto.getCodigoOriginal(),
                produto.getCodigoBarras(),
                produto.isBloqueadoParaCompras(),
                produto.getEstoque(),
                produto.getPrecoSemIpi(),
                produto.getPercentualIpiEntrada(),
                produto.getPrecoComIpi(),
                produto.getPesoUnidade(),
                produto.getAlturaUnidade(),
                produto.getLarguraUnidade(),
                produto.getComprimentoUnidade(),
                produto.getVolumeUnidadeM3(),
                produto.getVolumeLitros(),
                produto.getPesoCaixa(),
                produto.getAlturaCaixa(),
                produto.getLarguraCaixa(),
                produto.getComprimentoCaixa(),
                produto.getOrigem(),
                produto.getIndustrializado(),
                produto.getInsumo(),
                produto.getPercentualMaximoAproveitamentoIpi(),
                produto.getNumeroFci(),
                produto.getCategoria().getCodigo(),
                produto.getCategoria().getNome(),
                produto.getCategoria().getCaminho(),
                produto.getImagemUrl(),
                produto.isExibirNoSite(),
                produto.isDestaqueNaHome(),
                produto.isDisponivelUltimaImportacao(),
                produto.getUltimaImportacaoEm()
        );
    }
}
