spring.config.import=optional:file:${user.dir}/.env[.properties],optional:file:${user.dir}/../.env[.properties]
spring.application.name=dubaiMagazineSalvador
# DataSource configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=true

# JPA properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.url=${DB_URL}
spring.flyway.user=${DB_USERNAME}
spring.flyway.password=${DB_PASSWORD}
spring.flyway.locations=classpath:db/migration

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
app.upload.produtos-dir=${PRODUCT_IMAGES_DIR:uploads/produtos}

# api.Security.token.secret = ${JWT_SECRET:my-secret-key}
api.Security.token.secret=${JWT_SECRET}

# Alternate Server Port
server.port=8081
